In [1]:
import numpy as np
np.set_printoptions(precision=4, threshold=100, suppress=True)

<h2>Basics</h2>

In [2]:
np.zeros((128,128,3), dtype='int32')
np.ones(8)
np.eye(3, dtype='int8')
np.full((3,3), fill_value=5, dtype='float32')
np.random.random(5)
np.random.uniform(0, 10, (5,5)) # low, high, shape
np.random.randint(low=0, high=11, size=(30,1), dtype='int8') 
np.random.normal(0, 1, 100) # normal distribution p: mean, std, shape

np.arange(100).reshape(10,-1)
np.linspace(0, 100, 1001, endpoint=True)
np.logspace(0, 100, 20, base=2)

np.abs(np.random.normal(0,2,10))
np.log(np.abs(np.random.normal(0,2,10)))
np.sign(np.random.normal(0, 10, 10))
a = np.sign(np.random.normal(0, 10, 10))
a = np.where(a < 0, 0, a)
np.logical_not(a)

b = np.random.randint(10, 1000, 50)
np.argmin(b)
np.argmax(b)
np.sum(b)
np.min(b)
np.max(b)

b = np.random.normal(0, 2, 1000)
np.std(b)
np.var(b)
b

b[np.isnan(b)] = 0

<h2>Broadcasting</h2>

In [3]:
np.arange(3) + 5

np.zeros((3,3)) + np.arange(3)

np.arange(3).reshape(3,1) + np.arange(3)
np.arange(3).shape

np.arange(9).reshape(3,-1)

x = np.arange(3) #shape = (3,)
y = x[:, np.newaxis] #shape = (3, 1)
z = y * x #shape = (3, 3)

# spłaszczanie tablicy do 1D
z.flatten() #tworzy kopię tablicy
y.ravel() #tworzy widok tablicy gdy tylko to możliwe

a = np.arange(3).reshape(3,1)
a.squeeze() # usuwa wymiary o długości 1

array([0, 1, 2])

<h2>Stacking</h2>

In [238]:
a = np.random.randint(0, 100, (20, 4))
np.hstack((a, np.ones((a.shape[0], 1)))) #doklejenie kolumny jedynek
np.vstack((a, np.ones(a.shape[1]))) #doklejenie wiersza jedynek

a = np.random.randint(0,100, (3,3))
b = np.random.randint(0,100, (3,3))
c = np.random.randint(0,100, (3,3))

# dodanie wymiaru
a = a[np.newaxis, :]
b = np.expand_dims(b, axis=0)
c = np.expand_dims(c, axis=0)

# konkatenacja wg dowolnej istniejącej osi
# np zbiór kilku macierzy 2D
np.concatenate((a, b, c), axis=0) 

# np.concatenate - sklejanie wzdłuż istniejącej osi
# np.stack       - sklejanie wzdłuż nowej osi

# powyższy przykład można zrobić lepiej
c = np.random.randint(0,100, (3,3))
d = np.random.randint(0,100, (3,3))
e = np.random.randint(0,100, (3,3))

np.stack((c,d,e), axis=0)

array([[[29, 35, 10],
        [14, 76, 35],
        [92, 49,  6]],

       [[78, 83, 22],
        [21,  2,  3],
        [82, 72, 79]],

       [[77,  7, 80],
        [26, 10, 15],
        [ 4, 41, 75]]])

In [268]:
list = np.arange(10)

a = np.arange(10) * np.ones((3,1))

np.split(a, 3, axis=0) #podział wierszy
np.split(a, 5, axis=1) #podział kolumn

np.split(a, [2,3], axis=1) #lista indeksów gdzie ciąć

x = np.random.uniform(0, 100, size=(10000, 30))
np.random.shuffle(x) # przestasowanie wierszy

split_point = int(x.shape[0] * 0.8)
train, test = np.split(x, [split_point], axis=0)

print(np.mean(train), np.std(train))
print(np.mean(test), np.std(test))

50.01553379051276 28.8498463283924
49.94584752526941 28.89605318304822


<h2>Pliki - zapis i odczyt</h3>

In [289]:
M = np.random.uniform(size=(10,10,3))

np.save("arr.npy", M, allow_pickle=False)
arr = np.load("arr.npy")
np.sum(np.logical_not(arr == M))

X = np.random.randint(0, 100, size=(10,10), dtype='int8')

np.savetxt("x_arr.txt", X, fmt='%3d', delimiter=',') # fmt - format zapisu liczb

Z = np.loadtxt("x_arr.txt", dtype='int16', delimiter=',', skiprows=0)
Z

np.genfromtxt?


Signature:
np.genfromtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    skip_header=0,
    skip_footer=0,
    converters=None,
    missing_values=None,
    filling_values=None,
    usecols=None,
    names=None,
    excludelist=None,
    deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~",
    replace_space='_',
    autostrip=False,
    case_sensitive=True,
    defaultfmt='f%i',
    unpack=None,
    usemask=False,
    loose=True,
    invalid_raise=True,
    max_rows=None,
    encoding='bytes',
    *,
    like=None,
)
Docstring:
Load data from a text file, with missing values handled as specified.

Each line past the first `skip_header` lines is split at the `delimiter`
character, and characters following the `comments` character are discarded.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is `.gz` or `.bz2`, the file is first decompressed. Note
    

<h2>Algebra liniowa</h2>

In [ ]:
import numpy as np 

In [342]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(3,2)
a @ b # mnożenie macierzy

v = np.array([1,2,3])
np.dot(v,v) # iloczyn skalarny
np.linalg.norm(v) #norma wektora

z = np.random.randint(0, 10, (100,100))
np.linalg.det(z) #wyznacznik
x = np.ones((3,3))
np.linalg.matrix_rank(x) # ranga (rząd?) macierzy
np.trace(x) # ślad macierzy - suma el. na przekątnej

A = np.random.randint(0, 10, (3,3))
B = np.array([2, 5, 7])

np.linalg.solve(A, B) # rozwiązanie układu równań
#np.linalg.lstsq(A, B) # rozwiązanie najmniejszych kwadratów
np.linalg.inv(A) # odwrotność macierzy
np.linalg.eig(A) # wartości i wektory własne


(array([10.2575,  2.9332, -3.1907]),
 array([[-0.4759, -0.66  , -0.7433],
        [-0.7968,  0.7461,  0.0327],
        [-0.3722,  0.088 ,  0.6681]]))